### ISSUE TITLE
Previous character was neither a tab nor a space

### ISSUE THREAD

**Issue by basilgood** [chaoren/vim-expandtab#2]
Hi.
If the character before the cursor is not a space and not a tab but whatever character
and:```set noexpandtab softtabstop=2 tabstop=2``` , when hitting ```<Tab>``` will insert a tab.
```
--->bla--->bla
      ^<Tab>
```
And this is not correct.
Correct is to indent with tabs and align with spaces.
```
--->bla bla
      ^<Tab>
```
Thank you for the plugin.

**Comment by chaoren** [comment]
The plugin doesn't currently try to enforce "indent with tabs and align with spaces", it just tries to use whatever characters are before the tab. But maybe it does make sense to enforce it.

**Comment by basilgood** [comment]
OK! I understand now the plugin goal.
I would like that when it's not indentation,  ```Tab```  to put only spaces.
Like in IntelliJ IDEA. But nobody force me to hit key tab and not space after a character. :)
If you have the time and think it's worth to modify the plugin ...
Thank you!

**Comment by chaoren** [comment]
In your particular case I think it also makes sense to look at the character after the cursor, which is a space.

So the order of operation should be

1. Look at character before cursor,
    1. if it's tab use tab,
    2. if it's space use space.
2. Otherwise, look at character after cursor,
    1. if it's tab use tab,
    2. if it's space use space.
3. Otherwise, if at the start of the line, respect `expandtab`.
4. Otherwise, use space for alignment.

**Comment by basilgood** [comment]
Yes indeed.
It's clear that the plugin works correctly. This was the desired behavior.

**Comment by chaoren** [comment]
That comment is just my proposal. I still have to implement it.

**Comment by chaoren** [comment]
I changed my mind. Spaces for alignment is not universally adopted. For example in the vim help docs. I've decided to only look at characters before and after the cursor.

**Comment by basilgood** [comment]
Ok!
I respect your decision.
After the last changes the behavior is almost what I wanted.
One thing I would like, to respect ```pumvisible()```.
I can't select with tab when autocomplete because it inserts a tab.

**Comment by chaoren** [comment]
~~I also use `pumvisible()` but unfortunately you'll have to handle it yourself because `<Tab>` doesn't do anything by default. I think both `<C-Y>` (accept match) and `<C-N>` (move to next match) are reasonable choices so I'm not going to hardcode them in the plugin. I've added a note about how to handle `pumvisible()` in the README and help docs.~~

~~Add this to your vimrc:~~

```vim
let g:expandtab_nomap = 1
inoremap <Plug>ExpandTab <Tab>
imap <expr><Tab> pumvisible() ? '<C-Y>' : '<Plug>ExpandTab'
```

**Comment by chaoren** [comment]
Actually, the plugin can handle this automatically by checking `maparg()`. Thanks for bringing this up. Actually simplifies my own vimrc lol. You don't need to do anything from the previous comment. Just leave whatever `pumvisible` mapping you had for `<Tab>`.

**Comment by basilgood** [comment]
Ah!!! mapset() it's available only on vim and I'm on neovim.
```E117: Unknown function: mapset```

**Comment by chaoren** [comment]
Ah that sucks. But you do have `maparg` right? I can work around a missing `mapset`.

**Comment by chaoren** [comment]
Please try it now.

**Comment by basilgood** [comment]
Works perfectly without any additional settings.
Very good job.
Thank you very much.
